#![cfg(test)]
extern crate std;

use super::*;
use soroban_sdk::{
    testutils::{Address as _, Ledger},
    token, Address, Bytes, BytesN, Env,
};

fn setup(env: &Env) -> (InsurancePoolClient<'static>, token::Client<'static>, Address, Address, BytesN<32>, BytesN<32>) {
    env.mock_all_auths();
    env.ledger().with_mut(|li| {
        li.timestamp = 1000;
    });
    let admin = Address::generate(env);
    let holder = Address::generate(env);
    let token_address = env.register_stellar_asset_contract_v2(admin.clone()).address();
    let token = token::Client::new(env, &token_address);
    let token_admin = token::StellarAssetClient::new(env, &token_address);
    let contract_id = env.register(InsurancePool, ());
    let client = InsurancePoolClient::new(env, &contract_id);
    
    token_admin.mint(&holder, &100_000);
    token_admin.mint(&client.address, &100_000); 

    client.init(&admin, &token.address);
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_public_key_x = BytesN::from_array(env, raw_public_inputs[128..160].try_into().unwrap());
    let oracle_public_key_y = BytesN::from_array(env, raw_public_inputs[160..192].try_into().unwrap());
    client.set_oracle_key(&oracle_public_key_x, &oracle_public_key_y);
    let oracle = BytesN::from_array(env, &[7; 32]);
    let nullifier = BytesN::from_array(env, &[8; 32]);
    (client, token, admin, holder, oracle, nullifier)
}

#[test]
fn test_create_buy_fund() {
    let env = Env::default();
    let (client, token, _admin, holder, _oracle, _nullifier) = setup(&env);

    let product_id = client.create_product(&10, &1000, &180);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);

    assert_eq!(policy_id, 0);
    assert_eq!(token.balance(&client.address), 100_010); // 100k + 10 premium
    assert_eq!(token.balance(&holder), 99_990); // 100k - 10 premium
    assert_eq!(client.get_policy(&policy_id).holder, holder);
}

#[test]
fn test_claim_success_payout() {
    let env = Env::default();
    let (client, token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);
    
    // Load real proof and public inputs generated by TS fixture
    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    
    // The fixture binds policy_id=1, threshold=180, oracle commitment, and nullifier into verifier public inputs.
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());
    let oracle_public_key_x = BytesN::from_array(&env, raw_public_inputs[128..160].try_into().unwrap());
    let oracle_public_key_y = BytesN::from_array(&env, raw_public_inputs[160..192].try_into().unwrap());

    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());
    let expected_packed = InsurancePool::pack_public_inputs(
        &env,
        oracle_commitment.clone(),
        policy_id,
        180,
        nullifier.clone(),
        oracle_public_key_x.clone(),
        oracle_public_key_y.clone(),
        payout_recipient.clone(),
        verifier_domain.clone(),
    );
    
    assert_eq!(expected_packed.to_alloc_vec(), raw_public_inputs.to_vec());
    assert_eq!(client.get_oracle_key_x(), oracle_public_key_x);
    assert_eq!(client.get_oracle_key_y(), oracle_public_key_y);

    // Admin publishes the real event
    client.publish_event(&policy_id, &oracle_commitment);

    // Holder claims using the real proof
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);

    assert_eq!(token.balance(&client.address), 100_020 - 1000); // 100k + two premiums - payout
    assert_eq!(token.balance(&holder), 99_980 + 1000); // 100k - two premiums + payout
    assert!(client.nullifier_used(&nullifier));
    assert_eq!(client.get_policy(&policy_id).paid, true);
}

#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn test_mutated_proof_rejected() {
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);
    
    let raw_proof = include_bytes!("../../../artifacts/proof_blob.bin");
    let mut mutated_proof = raw_proof.to_vec();
    mutated_proof[5] ^= 0xFF; // Mutate the proof slightly
    let proof = Bytes::from_slice(&env, &mutated_proof);
    
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());

    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());
    client.publish_event(&policy_id, &oracle_commitment);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn test_mutated_public_inputs_rejected() {
    // If we change the threshold in the product, the packed public inputs won't match the proof's expected public inputs.
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &181); // Mutated threshold! (181 instead of 180)
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);
    
    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());

    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());
    client.publish_event(&policy_id, &oracle_commitment);
    // This constructs public inputs with threshold=181 and passes them to the verifier, which should fail.
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn test_wrong_policy_id_rejected() {
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);

    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());
    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());

    client.publish_event(&policy_id, &oracle_commitment);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn test_wrong_event_commitment_rejected() {
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);

    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());
    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());
    let wrong_commitment = BytesN::from_array(&env, &[9; 32]);

    client.publish_event(&policy_id, &wrong_commitment);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn test_wrong_nullifier_rejected() {
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);

    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());
    let wrong_nullifier = BytesN::from_array(&env, &[9; 32]);

    client.publish_event(&policy_id, &oracle_commitment);
    client.claim(&policy_id, &proof, &wrong_nullifier, &payout_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn test_wrong_payout_recipient_rejected() {
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);

    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());
    let wrong_recipient = BytesN::from_array(&env, &[9; 32]);

    client.publish_event(&policy_id, &oracle_commitment);
    client.claim(&policy_id, &proof, &nullifier, &wrong_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn test_wrong_verifier_domain_rejected() {
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);

    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());
    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let wrong_domain = BytesN::from_array(&env, &[9; 32]);

    client.publish_event(&policy_id, &oracle_commitment);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &wrong_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #4)")]
fn test_double_claim_rejected() {
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);

    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());
    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());

    client.publish_event(&policy_id, &oracle_commitment);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #10)")]
fn test_rotated_oracle_key_rejects_old_proof() {
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, _nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);
    
    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());

    let rotated_x = BytesN::from_array(&env, &[9; 32]);
    let rotated_y = BytesN::from_array(&env, &[10; 32]);
    client.set_oracle_key(&rotated_x, &rotated_y);
    assert_eq!(client.get_oracle_key_x(), rotated_x);
    assert_eq!(client.get_oracle_key_y(), rotated_y);

    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());
    client.publish_event(&policy_id, &oracle_commitment);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #12)")]
fn test_claim_without_oracle_key_rejected() {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().with_mut(|li| {
        li.timestamp = 1000;
    });
    let admin = Address::generate(&env);
    let holder = Address::generate(&env);
    let token_address = env.register_stellar_asset_contract_v2(admin.clone()).address();
    let token = token::Client::new(&env, &token_address);
    let token_admin = token::StellarAssetClient::new(&env, &token_address);
    let contract_id = env.register(InsurancePool, ());
    let client = InsurancePoolClient::new(&env, &contract_id);

    token_admin.mint(&holder, &100_000);
    token_admin.mint(&client.address, &100_000);
    client.init(&admin, &token.address);

    let product_id = client.create_product(&10, &1000, &180);
    let _dummy = client.buy_policy(&holder, &product_id, &3600);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);
    let proof = Bytes::from_slice(&env, include_bytes!("../../../artifacts/proof_blob.bin"));
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());

    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());
    client.publish_event(&policy_id, &oracle_commitment);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #11)")]
fn test_claim_without_event() {
    let env = Env::default();
    let (client, _token, _admin, holder, _oracle, nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let policy_id = client.buy_policy(&holder, &product_id, &3600);
    let proof = Bytes::from_array(&env, &[1, 2, 3]);

    let payout_recipient = BytesN::from_array(&env, &[0; 32]);
    let verifier_domain = BytesN::from_array(&env, &[0; 32]);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
}

#[test]
#[should_panic(expected = "Error(Contract, #5)")]
fn test_expired_policy_rejected() {
    let env = Env::default();
    let (client, _token, _admin, holder, oracle, nullifier) = setup(&env);
    let product_id = client.create_product(&10, &1000, &180);
    let policy_id = client.buy_policy(&holder, &product_id, &1);
    
    env.ledger().with_mut(|li| {
        li.timestamp = 1002;
    });
    
    client.publish_event(&policy_id, &oracle);
    let proof = Bytes::from_array(&env, &[1, 2, 3]);
    let payout_recipient = BytesN::from_array(&env, &[0; 32]);
    let verifier_domain = BytesN::from_array(&env, &[0; 32]);
    client.claim(&policy_id, &proof, &nullifier, &payout_recipient, &verifier_domain);
}

#[test]
fn test_verify_public_input_packing() {
    let env = Env::default();
    
    // Read the known-good public inputs from Barretenberg
    let raw_public_inputs = include_bytes!("../../../artifacts/public_inputs.bin");
    
    // The public inputs consist of 18 fields (each 32 bytes Big Endian):
    // 0..32: Oracle Commitment
    // 32..64: Policy ID
    // 64..96: Threshold
    // 96..128: Nullifier
    // 128..160: Oracle public key X
    // 160..192: Oracle public key Y
    // 192..576: domain marker fields 6..17
    let oracle_commitment = BytesN::from_array(&env, raw_public_inputs[0..32].try_into().unwrap());
    
    // The policy ID used in fixture is 1
    let policy_id = 1u64;
    
    // The threshold used in fixture is 180
    let threshold = 180u64;
    
    let nullifier = BytesN::from_array(&env, raw_public_inputs[96..128].try_into().unwrap());
    let oracle_public_key_x = BytesN::from_array(&env, raw_public_inputs[128..160].try_into().unwrap());
    let oracle_public_key_y = BytesN::from_array(&env, raw_public_inputs[160..192].try_into().unwrap());
    
    let payout_recipient = BytesN::from_array(&env, raw_public_inputs[192..224].try_into().unwrap());
    let verifier_domain = BytesN::from_array(&env, raw_public_inputs[224..256].try_into().unwrap());
    
    // Pack using the exact same function the contract uses
    let packed = InsurancePool::pack_public_inputs(
        &env,
        oracle_commitment,
        policy_id,
        threshold,
        nullifier,
        oracle_public_key_x,
        oracle_public_key_y,
        payout_recipient,
        verifier_domain,
    );
    
    // Assert byte-for-byte equality with bb's output
    assert_eq!(packed.to_alloc_vec(), raw_public_inputs.to_vec(), "Packed public inputs must exactly match Barretenberg public inputs");
}
